# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BL-O4xYzX9xV7mitWYtGrUkTUvhpkXAa

# Tokenizer
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

# Tokenizer
with open("mixed_ipa_corpus.txt", "r", encoding="utf-8") as f:
    text = f.read()

ipa_list = sorted(list(set(text)))
print(ipa_list)


id2ipa = {i: char for i, char in enumerate(ipa_list)}
ipa2id = {char: i for i, char in enumerate(ipa_list)}

print(ipa2id)
print(id2ipa)

data = torch.tensor([ipa2id[c] for c in text], dtype=torch.long)
print(f"total char num {len(data)}")
print(data[:100])

n = int(0.9 * len(data)) # 90%for Training、10% for testing
train_data = data[:n]
val_data = data[n:]

torch.manual_seed(1337) # consting seed

batch_size = 32  # batch size for 1 shot
block_size = 8   # max len of a word

def get_batch(split):
    # "train" for training data
    # "test" for testing data
    data_source = train_data if split == 'train' else val_data

    # getting random starting point
    ix = torch.randint(len(data_source) - block_size, (batch_size,))

    # x: input、y: the char that next to x
    x = torch.stack([data_source[i : i+block_size] for i in ix])
    y = torch.stack([data_source[i+1 : i+block_size+1] for i in ix])

    return x, y

# 1 batch test
xb, yb = get_batch('train')
print("---")
print("inputting x data(batch_size, block_size):", xb.shape)
print("Answer y data(batch_size, block_size):", yb.shape)

# 辞書のサイズ（発見されたIPAの種類数）
vocab_size = len(ipa2id)
n_embd = 64 # 次元数（脳の神経の太さ。今回は64で十分です）

class CharTransformer(nn.Module):
    def __init__(self):
        super().__init__()
        # 1. 文字IDを、AIが計算しやすい64次元のベクトル（意味の塊）に変換する層
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)

        # 2. 文字の「位置（何文字目か）」を教える層（これがないと順番が理解できない）
        self.position_embedding_table = nn.Embedding(block_size, n_embd)

        # 3. Transformerのメインエンジン（今回はシンプルに2層）
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=n_embd,
            nhead=4,
            dim_feedforward=128,
            batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=2)

        # 4. 最後にまた「IDごとの確率」に戻すための出力層
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape # B:バッチサイズ, T:文字の長さ

        # 文字の埋め込みベクトル ＋ 位置情報のベクトル を足し合わせる
        tok_emb = self.token_embedding_table(idx)
        pos = torch.arange(0, T, dtype=torch.long)
        pos_emb = self.position_embedding_table(pos)
        x = tok_emb + pos_emb

        # 未来の文字をカンニングできないようにするマスク（超重要！）
        mask = nn.Transformer.generate_square_subsequent_mask(T)

        # Transformerブロックに流し込む
        x = self.transformer(x, mask=mask, is_causal=True)

        # 各トークンの「次の文字」の予測スコア（logits）
        logits = self.lm_head(x)

        # targets（正解データ）が渡された場合は、答え合わせをして誤差（Loss）を計算
        if targets is None:
            loss = None
        else:
            # PyTorchのcross_entropy関数の仕様に合わせて形状を平たくする
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

# モデルをインスタンス化
model = CharTransformer()

# 先ほど作成したテスト用のミニバッチ(xb, yb)を流し込んでみる
logits, loss = model(xb, yb)

print("出力データの形状 (B*T, 辞書サイズ):", logits.shape)
print(f"初期状態の誤差 (Loss): {loss.item():.4f}")

# =========================================
# 5. 最適化アルゴリズム（Optimizer）のセット
# =========================================
# AIの学習において最も優秀で定番な「AdamW」を使います
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

max_iters = 3000      # 学習のループ回数
eval_interval = 300   # Lossを表示する間隔

print("🚀 学習スタート！Lossが下がっていくのを見守りましょう...")

for iter in range(max_iters):
    # 1. ミニバッチ（学習データ）を取得
    xb, yb = get_batch('train')

    # 2. 順伝播：モデルに予測させ、正解との誤差（Loss）を計算
    logits, loss = model(xb, yb)

    # 3. 逆伝播：誤差をもとに、脳内のパラメーターをどう修正すべきか計算
    optimizer.zero_grad(set_to_none=True) # 前回の計算結果（勾配）をリセット
    loss.backward()                       # 誤差を逆伝播

    # 4. パラメーターの更新：実際に脳のネットワークを少しだけ賢くする
    optimizer.step()

    # 一定間隔で現在のLossを表示して進捗を確認
    if iter % eval_interval == 0:
        print(f"Step {iter}: Loss = {loss.item():.4f}")

print(f"🎉 学習完了！最終Loss: {loss.item():.4f}")

# =========================================
# 6. 未知の人工言語（IPA）の生成！
# =========================================
# 最初はID 0のトークン（おそらく改行など）から生成をスタートさせます
context = torch.zeros((1, 1), dtype=torch.long)

# 何文字のIPAを生成するか
max_new_tokens = 300

print("🧠 AIが思考中（言語を生成しています）...\n")

for _ in range(max_new_tokens):
    # 現在の文脈（直近の block_size 文字）だけを切り出して入力
    idx_cond = context[:, -block_size:]

    # モデルに予測させる
    logits, _ = model(idx_cond)

    # 最後の文字の予測確率（logits）だけを取り出す
    logits = logits[:, -1, :]
    probs = F.softmax(logits, dim=-1)

    # 確率に基づいて次の文字を1つサンプリング（ガチャを回す）
    idx_next = torch.multinomial(probs, num_samples=1)

    # 予測した文字を文脈に追加して、次のループへ
    context = torch.cat((context, idx_next), dim=1)

# 生成されたIDの配列（テンソル）を普通のPythonのリストに変換
generated_ids = context[0].tolist()

# IDをIPA記号（テキスト）に戻す
generated_text = "".join([id2ipa[i] for i in generated_ids])

print("=========================================")
print("🎙️ 生成された未知の言語（IPA）")
print("=========================================\n")
print(generated_text)
print("\n=========================================")